#version 460 core

#include "noise.glsl"

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform PushConstants {
    layout(offset = 0) uint frame_index;
} push_const;

layout(set = 0, binding = 0, rgba32f) restrict writeonly uniform image2D image;

void main() {
    uvec3 data = uvec3(gl_GlobalInvocationID.xy, push_const.frame_index);
    vec4 color = vec4(hash(data), 1.0);

    imageStore(image, ivec2(gl_GlobalInvocationID.xy), color);
}