#version 460 core

// Adapted from:
// https://github.com/gl-transitions/gl-transitions/blob/master/transitions/
// b62319705bc54ab2597c36a3694c2476f8f52495
//
// Author:fkuteken
// License: MIT
// ported by gre from https://gist.github.com/fkuteken/f63e3009c1143950dee9063c3b83fb88

#include "_defs.glsl"

layout(push_constant) uniform PushConstants {
    layout(offset = 0) float progress;
    layout(offset = 16) vec4 bgcolor; // = vec4(0.0, 0.0, 0.0, 1.0)
} push_const;

vec2 ratio2 = vec2(1.0, 1.0);
float s = pow(2.0 * abs(push_const.progress - 0.5), 3.0);

vec4 transition(vec2 p) {
  float dist = length((vec2(p) - 0.5) * ratio2);
  return mix(
    push_const.progress < 0.5 ? getFromColor(p) : getToColor(p), // branching is ok here as we statically depend on push_const.progress uniform (branching won't change over pixels)
    push_const.bgcolor,
    step(s, dist)
  );
}

#include "_main.glsl"
