#version 460 core

// Adapted from:
// https://github.com/gl-transitions/gl-transitions/blob/master/transitions/
// b62319705bc54ab2597c36a3694c2476f8f52495
//
// Author:Fernando Kuteken
// License: MIT

#include "_defs.glsl"

layout(push_constant) uniform PushConstants {
    layout(offset = 0) float progress;
    layout(offset = 8) vec2 center; // = vec2(0.5, 0.5);
    layout(offset = 16) vec4 backColor; // = vec3(0.1, 0.1, 0.1, PAD);
} push_const;

vec4 transition (vec2 uv) {
  
  float distance = length(uv - push_const.center);
  float radius = sqrt(8.0) * abs(push_const.progress - 0.5);
  
  if (distance > radius) {
    return vec4(push_const.backColor.xyz, 1.0);
  }
  else {
    if (push_const.progress < 0.5) return getFromColor(uv);
    else return getToColor(uv);
  }
}

#include "_main.glsl"
