#version 460 core

// Adapted from:
// https://github.com/gl-transitions/gl-transitions/blob/master/transitions/
// b62319705bc54ab2597c36a3694c2476f8f52495
//
// Author:haiyoucuv
// License: MIT

#include "_defs.glsl"

layout(push_constant) uniform PushConstants {
    layout(offset = 0) float progress;
} push_const;

vec4 transition (vec2 uv) {
  
  vec4 coordTo = getToColor(uv);
  vec4 coordFrom = getFromColor(uv);
  
  return mix(
    getFromColor(coordTo.rg),
    getToColor(uv),
    push_const.progress
  );

}

#include "_main.glsl"
