#version 460 core

// Adapted from:
// https://github.com/gl-transitions/gl-transitions/blob/master/transitions/
// b62319705bc54ab2597c36a3694c2476f8f52495
//
// Author:gre
// License: MIT

#include "_defs.glsl"

layout(push_constant) uniform PushConstants {
    layout(offset = 0) float progress;
    layout(offset = 4) float smoothness; // = 0.5
    layout(offset = 8) vec2 direction; // = vec2(1.0, -1.0)
} push_const;

 
const vec2 center = vec2(0.5, 0.5);
 
vec4 transition (vec2 uv) {
  vec2 v = normalize(push_const.direction);
  v /= abs(v.x)+abs(v.y);
  float d = v.x * center.x + v.y * center.y;
  float m =
    (1.0-step(push_const.progress, 0.0)) * // there is something wrong with our formula that makes m not equals 0.0 with push_const.progress is 0.0
    (1.0 - smoothstep(-push_const.smoothness, 0.0, v.x * uv.x + v.y * uv.y - (d-0.5+push_const.progress*(1.+push_const.smoothness))));
  return mix(getFromColor(uv), getToColor(uv), m);
}

#include "_main.glsl"
