#version 460 core

// Adapted from:
// https://github.com/gl-transitions/gl-transitions/blob/master/transitions/
// b62319705bc54ab2597c36a3694c2476f8f52495
//
// Author:gre
// License: MIT

#include "_defs.glsl"

layout(push_constant) uniform PushConstants {
    layout(offset = 0) float progress;
    layout(offset = 4) float colorPhase; // = 0.4 ; // if 0.0, there is no black phase, if 0.9, the black phase is very important
    layout(offset = 16) vec3 color;// = vec3(0.0)
} push_const;

vec4 transition (vec2 uv) {
  return mix(
    mix(vec4(push_const.color, 1.0), getFromColor(uv), smoothstep(1.0-push_const.colorPhase, 0.0, push_const.progress)),
    mix(vec4(push_const.color, 1.0),   getToColor(uv), smoothstep(    push_const.colorPhase, 1.0, push_const.progress)),
    push_const.progress);
}

#include "_main.glsl"
