#version 460 core

// Adapted from:
// https://github.com/gl-transitions/gl-transitions/blob/master/transitions/
// b62319705bc54ab2597c36a3694c2476f8f52495
//
// Author:Xaychru
// License: MIT
// ported by gre from https://gist.github.com/Xaychru/ce1d48f0ce00bb379750

#include "_defs.glsl"

layout(push_constant) uniform PushConstants {
    layout(offset = 0) float progress;
    layout(offset = 4) float smoothness; // = 1.0
} push_const;

const float PI = 3.141592653589;

vec4 transition(vec2 p) {
  vec2 rp = p*2.-1.;
  return mix(
    getToColor(p),
    getFromColor(p),
    smoothstep(0., push_const.smoothness, atan(rp.y,rp.x) - (push_const.progress-.5) * PI * 2.5)
  );
}

#include "_main.glsl"
