#version 460 core

// Adapted from:
// https://github.com/gl-transitions/gl-transitions/blob/master/transitions/
// b62319705bc54ab2597c36a3694c2476f8f52495
//
// Author:towrabbit
// License: MIT

#include "_defs.glsl"

layout(push_constant) uniform PushConstants {
    layout(offset = 0) float progress;
} push_const;

float random (vec2 st) {
    return fract(sin(dot(st.xy,vec2(12.9898,78.233)))*43758.5453123);
}
vec4 transition (vec2 uv) {
  vec4 leftSide = getFromColor(uv);
  vec2 uv1 = uv;
  vec2 uv2 = uv;
  float uvz = floor(random(uv1)+push_const.progress);
  vec4 rightSide = getToColor(uv);
  float p = push_const.progress*2.0;
  return mix(leftSide,rightSide,uvz);
  return leftSide * ceil(uv.x*2.-p) + rightSide * ceil(-uv.x*2.+p);
}

#include "_main.glsl"
