#version 460 core

// Adapted from:
// https://github.com/gl-transitions/gl-transitions/blob/master/transitions/
// b62319705bc54ab2597c36a3694c2476f8f52495
//
// Author:Fabien Benetou
// License: MIT

#include "_defs.glsl"

layout(push_constant) uniform PushConstants {
    layout(offset = 0) float progress;
} push_const;

vec4 transition (vec2 uv) {
  float t = push_const.progress;
  
  if (mod(floor(uv.y*100.*push_const.progress),2.)==0.)
    t*=2.-.5;
  
  return mix(
    getFromColor(uv),
    getToColor(uv),
    mix(t, push_const.progress, smoothstep(0.8, 1.0, push_const.progress))
  );
}

#include "_main.glsl"
