[package]
name = "gfx-mock"
version = "0.1.0"
authors = ["John Wells <john@attackgoat.com>"]
edition = "2018"

[dependencies]
gfx-hal = { git = "https://github.com/gfx-rs/gfx", branch = "staging" }
raw-window-handle = "0.3"
