// NOTE: This program is intended to help "inflate" model vertex buffers which have been read from
// disk or the network. We do not store normal or tangent in the asset .pak file, so these
// attributes must be reconstructed at runtime; prior to rendering use.

#version 450

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

#include "calc_vertex_attrs.glsl"

// Reads a 32 bit index out of the 32 bit index buffer
uint read_idx(uint idx) {
    return idx_buf[idx];
}

#include "calc_vertex_attrs_fn.glsl"

void main() {
    calc_vertex_attrs();
}
