// NOTE: This program is intended to help "inflate" model vertex buffers which have been read from
// disk or the network. We do not store normal or tangent in the asset .pak file, so these
// attributes must be reconstructed at runtime; prior to rendering use.

// NOTE: This version of the program calculates attributes for U32-INDEXED vertices
// (POSITION+TEXCOORD -> POSITION/NORMAL/TANGENT/TEXCOORD)

#version 450

#include "calc_vertex_attrs_decl.glsl"

// Reads a 32 bit index out of the 32 bit index buffer
uint read_idx(uint idx) {
    return idx_buf[idx];
}

#include "calc_vertex_attrs_fns.glsl"

void main() {
    calc_vertex_attrs();
}
